services:
  php:
    image: yiisoftware/yii2-php:8.2-fpm-23.2.0-nginx
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
